### ISSUE TITLE
[bug] NPE and crash on the server related to using and identifying a book

### ISSUE THREAD

**Issue by noncom** [ssblur/scriptor#37]
**Mod Version (e.g. Fabric 0.3.4)**: scriptor-0.3.4-forge.jar

**What you expect to happen**:
No errors from the mod

**What actually happens**:
There's a NPE on the server from the mod:

```java
java.lang.NullPointerException: Cannot read field "key" because the return value of "com.ssblur.scriptor.helpers.DictionarySavedData.parseWord(String)" is null
        at TRANSFORMER/scriptor@0.3.4/com.ssblur.scriptor.helpers.DictionarySavedData.parse(DictionarySavedData.java:391)
        at TRANSFORMER/scriptor@0.3.4/com.ssblur.scriptor.item.Spellbook.m_7203_(Spellbook.java:72)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:266)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:286)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1089)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:29)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.TickTask.run(TickTask.java:18)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
```

The exception occurs when trying to use one of the found books. It occurs in 100% of the cases using the book.
It looks like an evolution of https://github.com/ssblur/scriptor/issues/17
It doesn't carsh the server when using the book -- there's simply no effect.
But it **does** crash the server when I try to use the identity scroll on the book. The crash log:
[crash-2023-04-13_23.54.16-server.txt](https://github.com/ssblur/scriptor/files/11239718/crash-2023-04-13_23.54.16-server.txt)

**Comment by ssblur** [comment]
Thank you for reporting! Can you attach `data/scriptor_dictionary.dat` from your world save? 
Which book is causing this? If it is default, you can just provide the title, but if it is custom, the full text of the book is appreciated.

**Comment by noncom** [comment]
Hey sure. The book title says "Instant Lightning", I've got it from a chest. Haven't yet gotten to writing my own spells 😄 

Screenshot:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/2920144/232633388-ae294833-a258-495b-b537-b8f807dd49bb.png">

The dictionary file:
[scriptor_dictionary.zip](https://github.com/ssblur/scriptor/files/11256565/scriptor_dictionary.zip)

**Comment by ssblur** [comment]
Thank you for reporting, I was able to replicate this issue and it has been resolved. Existing books will still not work, as they were generated incorrectly, but all spells generated from now on should work as expected. A version with this bugfix should be automatically released soon.
