### ISSUE TITLE
[bug] Scriptor 

### ISSUE THREAD

**Issue by HiroDeveloper** [ssblur/scriptor#88]
I get this error using scriptor for 1.19.2 

`[03:02:08] [Server thread/WARN]: ==========================================================
[03:02:08] [Server thread/INFO]: <Zennx3> jahsdja
[03:02:32] [Server thread/WARN]: ==========================================================
[03:02:32] [Server thread/WARN]: The below error did NOT cause a crash, this is debug info!
[03:02:32] [Server thread/ERROR]: Error:
java.lang.NullPointerException: Cannot read field "gender" because the return value of "com.ssblur.scriptor.helpers.DictionarySavedData.parseWord(String)" is null
        at com.ssblur.scriptor.helpers.DictionarySavedData.parse(DictionarySavedData.java:403) ~[scriptor-0.4.5-fabric.jar:?]
        at com.ssblur.scriptor.events.SpellChatEvents.received(SpellChatEvents.java:25) ~[scriptor-0.4.5-fabric.jar:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
        at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-6.5.85-fabric.jar:?]
        at dev.architectury.event.EventFactory$2.handleInvocation(EventFactory.java:81) ~[architectury-6.5.85-fabric.jar:?]
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar:?]
        at jdk.proxy2.$Proxy174.received(Unknown Source) ~[?:?]
        at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerCommon$25(EventHandlerImpl.java:93) ~[architectury-6.5.85-fabric.jar:?]
        at net.fabricmc.fabric.api.message.v1.ServerMessageEvents.lambda$static$0(ServerMessageEvents.java:46) ~[fabric-message-api-v1-5.0.7+93d8cb8290-b624de5b4dfd5388.jar:?]
        at net.minecraft.class_3324.handler$dck000$fabric-message-api-v1$onSendChatMessage(class_3324.java:8029) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_43673(class_3324.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_44155(class_3244.java:1444) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_45064(class_3244.java:1302) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]`

Adding 
[scriptor_dictionary.zip](https://github.com/ssblur/scriptor/files/13769223/scriptor_dictionary.zip)

**Comment by ssblur** [comment]
This is debug output. If I release another version for 1.19.2 I will suppress this output.
